In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_af2f6fddd4534648be3a64f49390c5cf = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='98u8RpH9cmpkfxGtDS-gE3j7pu_qrvCVt8m2xNyjde2M',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_af2f6fddd4534648be3a64f49390c5cf.get_object(Bucket='exam1-donotdelete-pr-iv3i36cdspczue',Key='winequality.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [4]:
x= dataset.iloc[:,0:11].values

In [5]:
x

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [6]:
y= dataset.iloc[:,11].values

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [8]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)           #previously cros_validation was used in sklearn


In [9]:
x_test

array([[ 10.8  ,   0.47 ,   0.43 , ...,   3.17 ,   0.76 ,  10.8  ],
       [  8.1  ,   0.82 ,   0.   , ...,   3.36 ,   0.53 ,   9.6  ],
       [  9.1  ,   0.29 ,   0.33 , ...,   3.26 ,   0.84 ,  11.7  ],
       ..., 
       [  9.1  ,   0.34 ,   0.42 , ...,   3.18 ,   0.55 ,  11.4  ],
       [  9.1  ,   0.765,   0.04 , ...,   3.29 ,   0.54 ,   9.7  ],
       [  8.2  ,   0.32 ,   0.42 , ...,   3.27 ,   0.55 ,  12.3  ]])

In [10]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

Using TensorFlow backend.


In [11]:
model=Sequential()#instance

In [12]:
model.add(Dense(input_dim=11,init="random_uniform",activation="relu",output_dim=6)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", activation="relu", input_dim=11, units=6)`
  if __name__ == '__main__':


In [13]:
model.add(Dense(output_dim=6,init="random_uniform",activation="relu"))# adding hidden layer similary like adding weights

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", activation="relu", units=6)`
  if __name__ == '__main__':


In [14]:
model.add(Dense(output_dim=1,init="random_uniform"))#adding output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", units=1)`
  if __name__ == '__main__':


In [15]:
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])#adam=batch gradent descent

In [16]:
model.fit(x_train,y_train,epochs=1000,batch_size=10)#epochs no of iteration 

Epoch 1/1000
1279/1279 [==============================] - 1s 457us/step - loss: 29.6042 - acc: 0.0000e+00
Epoch 2/1000
1279/1279 [==============================] - 0s 318us/step - loss: 8.6522 - acc: 0.0891
Epoch 3/1000
1279/1279 [==============================] - 0s 319us/step - loss: 4.7248 - acc: 0.1540
Epoch 4/1000
1279/1279 [==============================] - 0s 368us/step - loss: 3.3303 - acc: 0.1853
Epoch 5/1000
1279/1279 [==============================] - 0s 322us/step - loss: 2.1430 - acc: 0.2471
Epoch 6/1000
1279/1279 [==============================] - 0s 314us/step - loss: 1.2726 - acc: 0.3440
Epoch 7/1000
1279/1279 [==============================] - 0s 314us/step - loss: 0.8098 - acc: 0.4261
Epoch 8/1000
1279/1279 [==============================] - 0s 325us/step - loss: 0.6533 - acc: 0.4793
Epoch 9/1000
1279/1279 [==============================] - 0s 313us/step - loss: 0.6203 - acc: 0.5027
Epoch 10/1000
1279/1279 [==============================] - 0s 324us/step - loss: 0.606

In [17]:
y_predict=model.predict(x_test)

In [18]:
y_p=model.predict(np.array([[7.9,0.6,0.06,1.6,0.069,15,59,0.9964,3.3,0.46,9.4]]))



In [19]:
y_p

array([[ 5.17637444]], dtype=float32)

In [20]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=260)
rfc.fit(x_train,y_train)
from sklearn.metrics import accuracy_score
y_prediction=rfc.predict(x_test)
print(accuracy_score(y_test,y_prediction)*120)


87.375


In [21]:
model.save('winequality.h5')

In [22]:
get_ipython().system(u'tar -zcvf winequality.tgz winequality.h5')

winequality.h5


In [23]:
import watson_machine_learning_client

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [24]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [25]:
wml_credentials={

"url":"https://eu-gb.ml.cloud.ibm.com",
"access_key":"nnZiIDyW8JYMd_nIW-gAOs5UvZNTrN7s5NjgSdttEnSv",
"username":"9ec85d17-4cef-42ea-84a1-335b275bb6d3",
"password":"c8695961-6225-414b-b755-80a1ca2fdfef",
"instance_id": "305de161-527c-49c8-a2e9-469a6e830390" 
}

In [26]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [27]:
metadata={
    client.repository.ModelMetaNames.NAME:"keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME:"tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION:"1.5"
}

In [28]:
print(keras.__version__)

2.1.4


In [29]:
model_details=client.repository.store_model(model="winequality.tgz",meta_props=metadata)

In [30]:
model_id = model_details["metadata"]["guid"]
model_deployment_details = client.deployments.create(artifact_uid=model_id,name="deployment")



#######################################################################################

Synchronous deployment creation for uid: 'f37124a9-b48a-43e5-98ad-2a88240ed2f3' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='bee4e831-2905-4266-bd5f-fce75c89d817'
------------------------------------------------------------------------------------------------




In [31]:
model_id = model_details["metadata"]["guid"]

In [32]:
model_id

'f37124a9-b48a-43e5-98ad-2a88240ed2f3'

In [33]:
scoring_endpoint=client.deployments.get_scoring_url(model_deployment_details)

In [34]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/305de161-527c-49c8-a2e9-469a6e830390/deployments/bee4e831-2905-4266-bd5f-fce75c89d817/online'